[updates]

# automatically check if this is the latest version
# by requesting the latest version from a network server on application start
check_for_updates = true



[question_selector]

# how much to change the score every question
score_decay = 0.5

# how important is the score relative to time (in 100%/ms)
score_factor = 10000000.0

# how many questions to scan (less is more random)
confidence = 1.0



[delay]

# how long to show the "good" screen for (in ms)
good = 1000

# how long to show the "bad" screen for (in ms)
bad = 5000

# how long to hide the window for after every question (in ms) (0 to disable)
cooldown = 1000